<?php
// Neo HTML Protector delete options
// This is auto generate file

defined('ABSPATH') || defined('WP_UNINSTALL_PLUGIN') || die('Oh! No!');

function neohp_delete_options() {
	delete_option('neohp_agree');
	delete_option('neohp_agree_message_lang');
	delete_option('neohp_alert_a');
	delete_option('neohp_alert_beep');
	delete_option('neohp_alert_blur');
	delete_option('neohp_alert_c');
	delete_option('neohp_alert_copycut');
	delete_option('neohp_alert_ctrlshift');
	delete_option('neohp_alert_d');
	delete_option('neohp_alert_design');
	delete_option('neohp_alert_f12');
	delete_option('neohp_alert_i');
	delete_option('neohp_alert_j');
	delete_option('neohp_alert_k');
	delete_option('neohp_alert_message_lang');
	delete_option('neohp_alert_mouse');
	delete_option('neohp_alert_p');
	delete_option('neohp_alert_printscreen');
	delete_option('neohp_alert_r');
	delete_option('neohp_alert_s');
	delete_option('neohp_alert_sound');
	delete_option('neohp_alert_t');
	delete_option('neohp_alert_u');
	delete_option('neohp_blur');
	delete_option('neohp_confirm');
	delete_option('neohp_cookie1');
	delete_option('neohp_cookie2');
	delete_option('neohp_cookie3');
	delete_option('neohp_copycut_message');
	delete_option('neohp_ctrlshift_message');
	delete_option('neohp_dark');
	delete_option('neohp_debugmode_message');
	delete_option('neohp_deny_aibot');
	delete_option('neohp_deny_imagebot');
	delete_option('neohp_gdpr');
	delete_option('neohp_hash_bits');
	delete_option('neohp_hashjs_bits');
	delete_option('neohp_html_protect_head');
	delete_option('neohp_htmlcompress');
	delete_option('neohp_htmlprotect');
	delete_option('neohp_htmlprotect_message');
	delete_option('neohp_htmlprotectjs');
	delete_option('neohp_htmlsource_message');
	delete_option('neohp_imagedownload_message');
	delete_option('neohp_imagedownload_real');
	delete_option('neohp_imageprotect');
	delete_option('neohp_imageprotectjs');
	delete_option('neohp_injustice_ie');
	delete_option('neohp_injustice_ua');
	delete_option('neohp_islogin');
	delete_option('neohp_noagree');
	delete_option('neohp_nocookienojs_message');
	delete_option('neohp_nonce_bits');
	delete_option('neohp_nonce_expire');
	delete_option('neohp_nonceerror_message');
	delete_option('neohp_p3p');
	delete_option('neohp_printout_message');
	delete_option('neohp_printscreen_message');
	delete_option('neohp_redirect_times');
	delete_option('neohp_redirect_url');
	delete_option('neohp_rightclick_message');
	delete_option('neohp_save_message');
	delete_option('neohp_searchengine');
	delete_option('neohp_textselect_message');
	delete_option('neohp_transmission');
	delete_option('neohp_view-source_message_lang');
	delete_option('neohp_view_source_alert_asciiart');
}
